config/routes.rb
RegistrationDevise::Application.routes.draw do
  
  resources :users

  root "site#index"

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ActionController::Base
  
  def index
  
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.entries
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id]) 
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.create(user_params)
    
    redirect_to user_url(@user)
  end

  def update
    @user = User.find_by(id: params[:id])
    
    redirect_to user_url(@user)
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    
    redirect_to users_url
  end

  private
  
  def user_params
    params.require(:user).permit(
      :name
    )

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title WHubProject
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    p.notice= notice
    p.alert= alert
    = yield
    

app/views/site/index.html.erb
<h1> Index page </h1>
<h2> Hello users! </h2>

app/views/users/_form.html.slim
 = form_for @user do |f| 
  = f.label :name, "Name"
  = f.text_field :name, class: "form-control"
  = f.submit, class: "button btn btn-success" 

app/views/users/edit.html.slim
= render partial: 'form'

app/views/users/index.html.slim
- @users.each do |s|
  p #{s.name}

  => link_to "Show", user_url(s), class: "btn btn-primary btn-xs"
  => link_to "Edit", edit_user_url(s), class: "btn btn-info btn-xs"
  => link_to "Delete", user_url(s), method: :delete, confirm: "Are you sure?", class: "btn btn-danger btn-xs"
  br
  br

app/views/users/new.html.slim
== render 'form'

app/views/users/show.html.slim
h1 Show page
p #{@user.name}

=> link_to "Users", users_url(), class: "btn btn-primary btn-xs"